name: CI

on: [push]

jobs:
  sast_scan:
    name: Run Bandit Scan
    runs-on: ubuntu-latest

    steps:
    - name:  Chekout Code
      uses:  actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with: 
        pythin_version: 3.8

    - name: install Bandit
      run: pip install bandit

    - name: Run Bandit Scan
      run: bandit -ll -ii -r . -f json -o bandit-report.json

    - name: upload atrifact
      uses: actions/upload-artifact@v4.6.2
      if: always()
      with:
        name: bandit-findings
        path: bandit-report.json
        
  image_scan:
    name: Build Image and Run Docker Image Scan
    runs-on: ubuntu-latest

    steps:
    - name:  Chekout Code
      uses:  actions/checkout@v2

    - name: setup docker
      uses: docker/setup-docker-action@v4.3.0
      with: 
         version: 'v24.0.9'
    
    - name:  Build Docker Image
      run:  docker build -f Dockerfile -t myapp:latest .

    - name: Docker Scout Scan
      run: |
        curl -fsSL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh -o install-scout.sh
        sh install-scout.sh
        docker scout quickview
        docker scout cves
    
      

        
    
